#pragma checksum "JellyCharting.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "327114D40B834C2FA4B114031E8E5FA6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DataVisualizationDemos;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.DataVisualization.Charting;
using System.Windows.Controls.DataVisualization.Charting.Primitives;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DataVisualizationDemos {
    
    
    /// <summary>
    /// JellyCharting
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
    public partial class JellyCharting : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 8 "JellyCharting.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid LayoutRoot;
        
        #line default
        #line hidden
        
        
        #line 108 "JellyCharting.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ChartContainer;
        
        #line default
        #line hidden
        
        
        #line 114 "JellyCharting.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataVisualization.Charting.Chart ColumnChart;
        
        #line default
        #line hidden
        
        
        #line 120 "JellyCharting.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform ColumnChartScale;
        
        #line default
        #line hidden
        
        
        #line 163 "JellyCharting.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataVisualization.Charting.Chart LineChart;
        
        #line default
        #line hidden
        
        
        #line 169 "JellyCharting.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform LineChartScale;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DataVisualizationDemosWPF;component/jellycharting.xaml", System.UriKind.Relative);
            
            #line 1 "JellyCharting.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.LayoutRoot = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.ChartContainer = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.ColumnChart = ((System.Windows.Controls.DataVisualization.Charting.Chart)(target));
            
            #line 117 "JellyCharting.xaml"
            this.ColumnChart.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ShowColumnChartClick);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ColumnChartScale = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 5:
            this.LineChart = ((System.Windows.Controls.DataVisualization.Charting.Chart)(target));
            
            #line 166 "JellyCharting.xaml"
            this.LineChart.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ShowLineChartClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.LineChartScale = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 7:
            
            #line 229 "JellyCharting.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.MoreJelly);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

