#pragma checksum "PerformanceTweaks.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "62188D4FFDF4C7213083232DFD64847B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.DataVisualization.Charting;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DataVisualizationDemos {
    
    
    /// <summary>
    /// PerformanceTweaks
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
    public partial class PerformanceTweaks : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 22 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Reset;
        
        #line default
        #line hidden
        
        
        #line 23 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CreateChart;
        
        #line default
        #line hidden
        
        
        #line 24 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddSeries;
        
        #line default
        #line hidden
        
        
        #line 25 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddCompatibleSeries;
        
        #line default
        #line hidden
        
        
        #line 26 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PointCount;
        
        #line default
        #line hidden
        
        
        #line 33 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Populate;
        
        #line default
        #line hidden
        
        
        #line 34 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ChangeValues;
        
        #line default
        #line hidden
        
        
        #line 44 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox NoVsm;
        
        #line default
        #line hidden
        
        
        #line 45 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox SimplifiedTemplate;
        
        #line default
        #line hidden
        
        
        #line 46 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox EfficientCollection;
        
        #line default
        #line hidden
        
        
        #line 47 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox AxisRanges;
        
        #line default
        #line hidden
        
        
        #line 48 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox TransitionDuration;
        
        #line default
        #line hidden
        
        
        #line 50 "PerformanceTweaks.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContentPresenter Container;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DataVisualizationDemosWPF;component/performancetweaks.xaml", System.UriKind.Relative);
            
            #line 1 "PerformanceTweaks.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Reset = ((System.Windows.Controls.Button)(target));
            
            #line 22 "PerformanceTweaks.xaml"
            this.Reset.Click += new System.Windows.RoutedEventHandler(this.Reset_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.CreateChart = ((System.Windows.Controls.Button)(target));
            
            #line 23 "PerformanceTweaks.xaml"
            this.CreateChart.Click += new System.Windows.RoutedEventHandler(this.CreateChart_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.AddSeries = ((System.Windows.Controls.Button)(target));
            
            #line 24 "PerformanceTweaks.xaml"
            this.AddSeries.Click += new System.Windows.RoutedEventHandler(this.AddSeries_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.AddCompatibleSeries = ((System.Windows.Controls.Button)(target));
            
            #line 25 "PerformanceTweaks.xaml"
            this.AddCompatibleSeries.Click += new System.Windows.RoutedEventHandler(this.AddSeries_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.PointCount = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.Populate = ((System.Windows.Controls.Button)(target));
            
            #line 33 "PerformanceTweaks.xaml"
            this.Populate.Click += new System.Windows.RoutedEventHandler(this.Populate_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.ChangeValues = ((System.Windows.Controls.Button)(target));
            
            #line 34 "PerformanceTweaks.xaml"
            this.ChangeValues.Click += new System.Windows.RoutedEventHandler(this.ChangeValues_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.NoVsm = ((System.Windows.Controls.CheckBox)(target));
            
            #line 44 "PerformanceTweaks.xaml"
            this.NoVsm.Checked += new System.Windows.RoutedEventHandler(this.TemplateChange_Checked);
            
            #line default
            #line hidden
            return;
            case 9:
            this.SimplifiedTemplate = ((System.Windows.Controls.CheckBox)(target));
            
            #line 45 "PerformanceTweaks.xaml"
            this.SimplifiedTemplate.Checked += new System.Windows.RoutedEventHandler(this.TemplateChange_Checked);
            
            #line default
            #line hidden
            return;
            case 10:
            this.EfficientCollection = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 11:
            this.AxisRanges = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 12:
            this.TransitionDuration = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 13:
            this.Container = ((System.Windows.Controls.ContentPresenter)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

